#!/bin/bash
# docker.sh — Generate docker-compose.yml for MC server
# Usage: ./docker.sh [--type paper] [--version 1.21.4] [--port 25565] [--ram 2G]
#
# Generates a docker-compose.yml using itzg/docker-minecraft-server image
# This is an alternative to bare-metal setup.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# ═══════════════════════════════════════════
#  Defaults
# ═══════════════════════════════════════════
SERVER_TYPE="paper"
MC_VERSION=""
PORT="25565"
RAM="2G"
COMPOSE_FILE="docker-compose.yml"
PROJECT_NAME="minecraft"
VOLUME_NAME="minecraft-data"
TZ="Asia/Jakarta"

# ═══════════════════════════════════════════
#  Parse args
# ═══════════════════════════════════════════
while [[ $# -gt 0 ]]; do
    case "$1" in
        --type)     SERVER_TYPE="$2";   shift 2 ;;
        --version)  MC_VERSION="$2";    shift 2 ;;
        --port)     PORT="$2";          shift 2 ;;
        --ram)      RAM="$2";           shift 2 ;;
        --project)  PROJECT_NAME="$2";  shift 2 ;;
        --volume)   VOLUME_NAME="$2";   shift 2 ;;
        --tz)       TZ="$2";           shift 2 ;;
        --output|-o) COMPOSE_FILE="$2"; shift 2 ;;
        --help|-h)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --type TYPE     Server type (paper/purpur/fabric) (default: paper)"
            echo "  --version VER   MC version (default: latest)"
            echo "  --port PORT     Server port (default: 25565)"
            echo "  --ram RAM       Max RAM (default: 2G)"
            echo "  --project NAME  Docker project name (default: minecraft)"
            echo "  --volume NAME   Docker volume name (default: minecraft-data)"
            echo "  --tz TZ         Timezone (default: Asia/Jakarta)"
            echo "  --output FILE   Output file (default: docker-compose.yml)"
            exit 0
            ;;
        *) echo "Unknown: $1"; exit 1 ;;
    esac
done

echo "========================================"
echo "  Docker Compose Generator"
echo "========================================"
echo "Type:    $SERVER_TYPE"
echo "Port:    $PORT"
echo "RAM:     $RAM"
echo "TZ:      $TZ"
echo ""

# ═══════════════════════════════════════════
#  Map type to itzg docker image
# ═══════════════════════════════════════════
case "$SERVER_TYPE" in
    paper)   TYPE_VAR="PAPER" ;;
    purpur)  TYPE_VAR="PURPUR" ;;
    fabric)  TYPE_VAR="FABRIC" ;;
    spigot)  TYPE_VAR="SPIGOT" ;;
    *)       TYPE_VAR="$SERVER_TYPE" ;;
esac

# ═══════════════════════════════════════════
#  Generate docker-compose.yml
# ═══════════════════════════════════════════
cat > "$COMPOSE_FILE" << EOF
# Auto-generated by mc-server docker.sh
# https://github.com/bianvigano/mc-server
# Docs: https://docker-minecraft-server.readthedocs.io/
#
# Usage:
#   docker compose up -d
#   docker compose logs -f
#   docker compose down
#   docker compose exec mc rcon-cli
#
# For config:
#   Edit server.properties in the volume, or use env vars below.

services:
  mc:
    image: itzg/minecraft-server
    container_name: ${PROJECT_NAME}-mc
    restart: unless-stopped
    ports:
      - "${PORT}:25565"
    environment:
      EULA: "TRUE"
      TYPE: "${TYPE_VAR}"
EOF

if [ -n "$MC_VERSION" ]; then
    echo "      VERSION: \"${MC_VERSION}\"" >> "$COMPOSE_FILE"
fi

cat >> "$COMPOSE_FILE" << EOF
      MEMORY: "${RAM}"
      TZ: "${TZ}"
      # === Common settings (uncomment to edit) ===
      # DIFFICULTY: normal
      # GAMEMODE: survival
      # MAX_PLAYERS: 20
      # MOTD: "My Minecraft Server"
      # ONLINE_MODE: "TRUE"
      # PVP: "TRUE"
      # VIEW_DISTANCE: 10
      # SIMULATION_DISTANCE: 10
      # SEED: ""
      # LEVEL_NAME: world
      #
      # === RCON (for stats/monitoring) ===
      # ENABLE_RCON: "TRUE"
      # RCON_PASSWORD: "changeme"
      # RCON_PORT: 25575
      #
      # === Performance ===
      # JAVA_FLAGS: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200"
      #
      # === Plugins (Paper/Purpur) ===
      # VERSION_CHANNEL: default
      #
      # === Mods (Fabric) ===
      # https://docker-minecraft-server.readthedocs.io/en/latest/mods-and-plugins/
    volumes:
      - ${VOLUME_NAME}:/data
    stdin_open: true
    tty: true
    stop_grace_period: 60s

volumes:
  ${VOLUME_NAME}:
    name: ${VOLUME_NAME}
EOF

echo "[OK] Generated: $COMPOSE_FILE"
echo ""
echo "Commands:"
echo "  docker compose up -d              Start server"
echo "  docker compose down               Stop server"
echo "  docker compose logs -f            View logs"
echo "  docker compose exec mc rcon-cli   RCON console"
echo "  docker compose exec mc bash       Shell into container"
echo "  docker compose pull               Update image"
echo "  docker compose up -d              Restart with new image"
echo ""
echo "Backup:"
echo "  docker run --rm -v ${VOLUME_NAME}:/data -v \$(pwd):/backup alpine \\"
echo "    tar czf /backup/mc-backup-\$(date +%Y%m%d).tar.gz -C /data ."
echo ""
echo "Plugins:"
echo "  ./plugins.sh install <slug>       # Install from Modrinth"
echo "  cp my-plugin.jar plugins/         # Manual install"
echo ""
echo "All set!"
